# Generated by Django 6.0.1 on 2026-01-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('repository', models.URLField(blank=True, null=True)),
                ('skills', models.ManyToManyField(related_name='projects', to='projects.skill')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
